version: "3.9"

services:
  backend:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: "304936888939.dkr.ecr.eu-central-1.amazonaws.com/production/backend:latest"
    container_name: "blog-backend"
    ports:
      - "3000:3000"
    volumes:
      - "/opt/automated-blog/data:/app/data"
    env_file: "/opt/automated-blog/.secrets"
    environment:
      PORT: "3000"
      FRONTEND_ORIGIN: "http://35.171.228.37"
      OPENROUTER_URL: "https://openrouter.ai/api/v1/chat/completions"
      LLM_MODEL: "mistralai/devstral-2512:free"
      ENABLE_DAILY_GENERATION: "true"
      ARTICLE_CRON: "*/1 * * * *"
      TITLE_MAX_LENGTH: "200"
      CONTENT_MAX_LENGTH: "20000"
      ARTICLES_PATH: "/app/data/articles.json"

networks:
  automated-blog:
