name: Frontend CI (CodeBuild Runner)

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/front.build.yml'
  # pull_request:
  #   paths:
  #     - 'frontend/**'

jobs:
  build-frontend:
    runs-on: codebuild-blog-frontend-${{ github.run_id }}-${{ github.run_attempt }}

    # defaults:
    #   run:
    #     working-directory: frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Log in to Amazon ECR
      #   run: |
      #     aws ecr get-login-password --region eu-central-1 \
      #     | docker login --username AWS --password-stdin 304936888939.dkr.ecr.eu-central-1.amazonaws.com

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        working-directory: frontend
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t production-frontend:${IMAGE_TAG} .

      - name: Tag and push image to ECR
        working-directory: frontend
        run: |
          ACCOUNT_ID=304936888939
          REGION=eu-central-1
          REPOSITORY=production/frontend
          IMAGE_TAG=${GITHUB_SHA::7}

          ECR_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPOSITORY}

          docker tag production-frontend:${IMAGE_TAG} ${ECR_URI}:${IMAGE_TAG}

          docker push ${ECR_URI}:${IMAGE_TAG}

          docker tag ${ECR_URI}:${IMAGE_TAG} ${ECR_URI}:latest
          docker push ${ECR_URI}:latest