name: Frontend - Bake image

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build-frontend:
    runs-on: codebuild-automated-blog-frontend-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set image tag (timestamp)
        run: |
          echo $(date +'%Y%m%d-%H%M')
          echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=public.ecr.aws/vend/moby/buildkit:buildx-stable-1

      - name: Build Docker image
        working-directory: frontend
        run: |
          echo "Using tag: ${IMAGE_TAG}"
          docker build -t production-frontend:${IMAGE_TAG} .

      - name: Tag and push image to ECR
        working-directory: frontend
        run: |
          REPOSITORY=production/frontend

          ECR_URI=${{ steps.login-ecr.outputs.registry }}/${REPOSITORY}

          docker tag production-frontend:${IMAGE_TAG} ${ECR_URI}:${IMAGE_TAG}

          docker push ${ECR_URI}:${IMAGE_TAG}

          docker tag ${ECR_URI}:${IMAGE_TAG} ${ECR_URI}:latest
          docker push ${ECR_URI}:latest
